### ISSUE TITLE
3화 fs모듈

### ISSUE THREAD

**Issue by ghostdeleted** [Ukong0324/Discord-JS-Tutorial#12]
https://github.com/Ukong0324/Discord-JS-Tutorial/blob/master/3%ED%99%94/README.MD

```md
이번에 필요한 모듈은 fs 입니다.
꼭 npm i fs --save로 모듈을 설치해주시길 바랍니다.
모듈 설치 하실줄 모르는 분은 __module_install.md__를 읽어주세요.
```

fs는 node.js의 기본 모듈입니다. npm i fs --save 라는 표현은 옮지 못한 표현인것 같습니다
현재 npmjs 의 fs모듈은 보안을 위해 npm에서 이름을 홀딩하고 있는 상태인것 같네요

https://nodejs.org/docs/latest-v14.x/api/fs.html

**Comment by Ukong0324** [comment]
추후에 수정하겠습니다
