### ISSUE TITLE
Its Bug!

### ISSUE THREAD

**Issue by filename24** [Ukong0324/Discord-JS-Tutorial#14]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined

[5화](https://github.com/Ukong0324/Discord-JS-Tutorial/blob/master/5%ED%99%94/Commands/Bot/help.js)

해당 내용의 15Line 에 오류가 납니다

**Comment by Ukong0324** [comment]
![image](https://user-images.githubusercontent.com/41337427/102807711-8233fa80-4402-11eb-910c-abf46026934b.png)
잘 됩니다
