### ISSUE TITLE
config.json을 불러오지 못합니다.

### ISSUE THREAD

**Issue by serverexplode7** [Ukong0324/Discord-JS-Tutorial#3]
cmd에서 node bot.js를 입력했을때 대충 해석해보면 config.json을 불러오지 못했다는거 같은에
어떻게 합니까?

**Comment by Ukong0324** [comment]
config.json이 메인(bot.js)와 같은 폴더에 있나요?

![image](https://user-images.githubusercontent.com/41337427/82743489-40c56900-9da7-11ea-8fb4-0daa2a55b96a.png)

에러가 발생하면 해당 에러와 같이 적어주시면 설명해드리기 편합니다.

**Comment by serverexplode7** [comment]
![image](https://user-images.githubusercontent.com/64202954/82743695-dd890600-9da9-11ea-9e6b-5598e98f4041.png)

모듈도 다 설치하고 json 파일에 토큰을 넣어도 실행 오류가 뜹니다.

**Comment by serverexplode7** [comment]
![image](https://user-images.githubusercontent.com/64202954/82743820-73716080-9dab-11ea-873d-fc18ea83a823.png)

**Comment by Ukong0324** [comment]
제가 소스코드 작성하면서 사용자쪽으로 생각을 안하고 적었네요 죄송합니다

**Comment by Ukong0324** [comment]
수정 후 다시 깃헙에 올리겠습니다
