### ISSUE TITLE
3화 에 나오는 bot.js에 있는 35번째 줄에 오류가 뜸니다

### ISSUE THREAD

**Issue by filename24** [Ukong0324/Discord-JS-Tutorial#4]
오류내용은 대충 이런거 입니다
비밀정보\index.js:38
    runCommand(command, msg, args, prefix).catch(e => console.error(e))
                                          ^

TypeError: Cannot read property 'catch' of undefined
    at Client.<anonymous> (비밀정보\index.js
:38:43)

**Comment by Ukong0324** [comment]
해당 에러를 확인하였습니다.

수정후 다시 알려드리겠습니다.

**Comment by Ukong0324** [comment]
해당 버그를 수정하였습니다.
