### ISSUE TITLE
3화 관련 불필요한 모듈 설치

### ISSUE THREAD

**Issue by dropdb220** [Ukong0324/Discord-JS-Tutorial#7]
fs는 안깔아도 기본으로 있는것 아닌가여;;;

**Comment by filename24** [comment]
그레도 모르는 유저에게 알리는겁니다

**Comment by Ukong0324** [comment]
> fs는 안깔아도 기본으로 있는것 아닌가여;;;

모듈 설치를 하실줄 모르는 분들을 위해서 fs로 예시를 들었습니다.
또한 가끔가다 fs 모듈이 설치 안되어 있는 개발자분들이 있어 예시로 채택하게 되었습니다.
